---
title: "Problem Set 1"
author: "Zach Koverman"
date: "2023-10-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("ISLR2")
```

## 2.3.1 Basic Commands

```{r Basic Commands i}
x <- c(1, 3, 2, 5)
x
x <- c(1, 6, 2)
x
y <- c(1, 4, 3)
y
```

``` {r Basic Commands ii}
length(x)
length(y)
x + y

ls()
rm(x, y)
ls()

x <- c(1, 6, 2)
y <- c(1, 4, 3)
ls()
rm(list = ls())
ls()
```

``` {r Basic Commands iii}
?matrix

x <- matrix(data = c(1, 2, 3, 4), nrow=2, ncol=2)
x
rm(x)
x <- matrix(data = c(1, 2, 3, 4), 2, 2)
x

matrix(c(1, 2, 3, 4), 2, 2, byrow=TRUE)
x
sqrt(x)
x^2
```

```{r Basic Commands iv}
x <- rnorm(50)
y <- x + rnorm(50, mean=50, sd=.1)
cor(x, y)

set.seed(1222)
rnorm(50)
set.seed(1303)
rnorm(50)

set.seed(3)
y <- rnorm(100)
mean(y)
var(y)
sqrt(var(y))
sd(y)
```

## 2.3.2 Graphics

```{r Graphics i}
x <- rnorm(100)
y <- rnorm(100)

?plot

plot(x, y)
plot(x, y, xlab = "this is the x-axis ", ylab = "this is the y-axis", main = "Plot of X vs. Y")
```

```{r Graphics ii}
pdf("Figure.pdf")
plot(x, y, col = "green")
dev.off()
```

``` {r Graphics iii}
x <- seq(1, 10)
x

x <- 1:10
x

x <- seq(-pi, pi, length=50)
```

```{r Graphics iv}
y <- x
f <- outer(x, y, function(x, y) cos(y) / (1 + x^2))

?contour
contour(x, y, f)
contour(x, y, f, nlevels=45, add=T)

fa <- (f - t(f)) / 2
contour(x, y, fa, nlevels = 15)
```

```{r Graphics v}
image(x, y, fa)
persp(x, y, fa)
persp(x, y, fa, theta=30)
persp(x, y, fa, theta=30, phi=20)
persp(x, y, fa, theta=30, phi=70)
persp(x, y, fa, theta=30, phi=40)
```

## 2.3.3 Indexing Data
```{r Indexing Data i}
A <- matrix(1:16, 4, 4)
A
A[2, 3]

A[c(1, 3), c(2, 4)] # include rows 1 & 3, col 2 & 4
A[1:3, 2:4] # include rows 1-3, col 2-4
A[1:2, ] # include all columns
A[, 1:2] # include all rows
A[1, ]
A[-c(1, 3), ]
A[-c(1, 3), -c(1, 3, 4)]

dim(A)
```

## 2.3.4 Loading Data
```{r Loading Data i}
Auto <- read.table("Auto.data")
View(Auto)
head(Auto)
```

```{r Loading Data ii}
Auto <- read.table("Auto.data", header=TRUE, na.strings="?", stringsAsFactors=TRUE)
View(Auto)
```

```{r Loading Data iii}
Auto <- read.csv("Auto.csv", na.strings="?", stringsAsFactors=TRUE)
View(Auto)
```

```{r Loading Data iv}
dim(Auto)
Auto[1:4, ]

Auto <- na.omit(Auto)
dim(Auto)

names(Auto)
```

## 2.3.5 Additional Graphical and Numerical Summaries
```{r Additional Summaries i}
# plot(cylinders, mpg)

plot(Auto$cylinders, Auto$mpg)

attach(Auto)
plot(cylinders, mpg)
```

```{r Additional Summaries ii}
cylinders <- as.factor(cylinders)

plot(cylinders, mpg)
plot(cylinders, mpg, col="red")
plot(cylinders, mpg, col="red", varwidth=TRUE)
plot(cylinders, mpg, col="red", varwidth=T, horizontal=T)
plot(cylinders, mpg, col="red", varwidth=T, xlab="cylinders", ylab="MPG")
```

```{r Additional Summaries iii}
hist(mpg)
hist(mpg, col=2)
hist(mpg, col=2, breaks=15)

pairs(Auto)
pairs(~ mpg + displacement + horsepower + weight + acceleration, data=Auto)
```

```{r Additional Summaries iv}
plot(horsepower, mpg)
identify(horsepower, mpg, name)

summary(Auto)
summary(mpg)
```